# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# What combinations to test
environment:
  github_release_token:
    secure: wfW7RWDvNKnF2haNaW7GVa/xi7Ot4yy6puIAsN2mjmHJQtQpx3XvH+6lf2Tr8Xr9
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"

platform:
  - x86
  - x64

image: Visual Studio 2015

artifacts:
  - path: build\**\*.tar.gz
    name: microtime_binary

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - IF %nodejs_version% LSS 4 npm install -g npm@2
  - IF %nodejs_version% GEQ 4 npm install -g npm
  - npm install -g node-gyp
  - npm install -g node-pre-gyp

  # work around an issue with node-gyp v3.3.1 and node 4x
  # https://github.com/nodejs/node-gyp/issues/921
  # (copied from libxmljs)
  - npm config set -g cafile=package.json
  - npm config set -g strict-ssl=false
  - npm config set registry http://registry.npmjs.org/

build_script:
  - npm install --msvs_version=2015

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - npm ls
  - npm test

after_test:
  - node-pre-gyp package 2>&1

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    artifact: microtime_binary
    auth_token: $(github_release_token)
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

after_deploy:
  - npm config delete -g cafile
  - npm config delete -g strict-ssl
  - npm config delete registry
  - node-pre-gyp clean
  - npm install --fallback-to-build=false
  - npm test
